In [1]:
%load_ext autoreload
%autoreload 2

In [12]:
import pandas as pd
import numpy as np
df = pd.read_csv('column_design_forces.csv')
df.head(16)

,Story,Column,UniqueName,Combo,Station,P,V2,V3,T,M2,M3
0,Story1,C2,3,ULS-1,0,-2247190.81,55287.21,27606.19,5743638.7,43486184.81,2.396569e+08
1,Story1,C2,3,ULS-1,1200,-2238370.81,55287.21,27606.19,5743638.7,10358759.51,1.733122e+08
2,Story1,C2,3,ULS-1,2400,-2229550.81,55287.21,27606.19,5743638.7,-22768665.79,1.069676e+08
3,Story1,C2,3,ULS-2,0,-2247190.81,55287.21,27606.19,5743638.7,43486184.81,2.396569e+08
4,Story1,C2,3,ULS-2,1200,-2238370.81,55287.21,27606.19,5743638.7,10358759.51,1.733122e+08
5,Story1,C2,3,ULS-2,2400,-2229550.81,55287.21,27606.19,5743638.7,-22768665.79,1.069676e+08
6,Story1,C2,3,UDConS3-1,0,-1777279.28,15596.75,16238.93,3378611.0,25580108.71,1.290383e+08
7,Story1,C2,3,UDConS3-1,1200,-1769719.28,15596.75,16238.93,3378611.0,6093387.95,1.103222e+08
8,Story1,C2,3,UDConS3-1,2400,-1762159.28,15596.75,16238.93,3378611.0,-13393332.82,9.160608e+07
9,Story1,C2,3,UDConS4-1,0,-1777279.28,15596.75,16238.93,3378611.0,25580108.71,1.290383e+08
10,Story1,C2,3,UDConS4-1,1200,-1769719.28,15596.75,16238.93,3378611.0,6093387.95,1.103222e+08
11,Story1,C2,3,UDConS4-1,2400,-1762159.28,15596.75,16238.93,3378611.0,-13393332.82,9.160608e+07
12,Story1,C2,3,UDConS5-1,0,-1088696.20,-40461.65,0.00,0.0,0.00,-2.853530e+07
13,Story1,C2,3,UDConS5-1,1200,-1083026.20,-40461.65,0.00,0.0,0.00,2.001868e+07
14,Story1,C2,3,UDConS5-1,2400,-1077356.20,-40461.65,0.00,0.0,0.00,6.857266e+07
15,Story1,C2,3,UDConS6-1,0,-1088696.20,-40461.65,0.00,0.0,0.00,-2.853530e+07

In [13]:
IDX = pd.IndexSlice
# Create the multi-index out of existing columns
results_df = df.set_index(["Story", "Column","UniqueName", "Combo", "Station"])

results_df['P'] = results_df['P'] * -1
results_df['section_depth'] = 700
results_df['section_width'] = 300
first_station_idx = results_df.index[::3]
last_station_idx = results_df.index[2::3]
first_df = results_df.loc[first_station_idx]
last_df = results_df.loc[last_station_idx]

final_df = pd.DataFrame( list(last_df.index.droplevel(['Story', 'Column', 'UniqueName', 'Combo'])), columns=['length_lu'])
first_df

                                                     P        V2        V3  \
Story  Column UniqueName Combo     Station
Story1 C2     3          ULS-1     0        2247190.81  55287.21  27606.19
                         ULS-2     0        2247190.81  55287.21  27606.19
                         UDConS3-1 0        1777279.28  15596.75  16238.93
                         UDConS4-1 0        1777279.28  15596.75  16238.93
                         UDConS5-1 0        1088696.20 -40461.65      0.00
                         UDConS6-1 0        1088696.20 -40461.65      0.00
       C8     15         ULS-1     0        2317562.11  46043.80 -86451.71
                         ULS-2     0        2317562.11  46043.80 -86451.71
                         UDConS3-1 0        1813947.61  27084.59 -63076.29
                         UDConS4-1 0        1813947.61  27084.59 -63076.29
                         UDConS5-1 0        1077396.78      0.00 -29219.04
                         UDConS6-1 0        1077396.78      0.00 -29219.04

                                                     T            M2  \
Story  Column UniqueName Combo     Station
Story1 C2     3          ULS-1     0        5743638.70  4.348618e+07
                         ULS-2     0        5743638.70  4.348618e+07
                         UDConS3-1 0        3378611.00  2.558011e+07
                         UDConS4-1 0        3378611.00  2.558011e+07
                         UDConS5-1 0              0.00  0.000000e+00
                         UDConS6-1 0              0.00  0.000000e+00
       C8     15         ULS-1     0       -6296160.18 -1.205567e+08
                         ULS-2     0       -6296160.18 -1.205567e+08
                         UDConS3-1 0       -3703623.64 -8.364637e+07
                         UDConS4-1 0       -3703623.64 -8.364637e+07
                         UDConS5-1 0              0.00 -3.043420e+07
                         UDConS6-1 0              0.00 -3.043420e+07

                                                      M3  section_depth  \
Story  Column UniqueName Combo     Station
Story1 C2     3          ULS-1     0        2.396569e+08            700
                         ULS-2     0        2.396569e+08            700
                         UDConS3-1 0        1.290383e+08            700
                         UDConS4-1 0        1.290383e+08            700
                         UDConS5-1 0       -2.853530e+07            700
                         UDConS6-1 0       -2.853530e+07            700
       C8     15         ULS-1     0        9.906112e+07            700
                         ULS-2     0        9.906112e+07            700
                         UDConS3-1 0        5.827125e+07            700
                         UDConS4-1 0        5.827125e+07            700
                         UDConS5-1 0        0.000000e+00            700
                         UDConS6-1 0        0.000000e+00            700

                                            section_width
Story  Column UniqueName Combo     Station
Story1 C2     3          ULS-1     0                  300
                         ULS-2     0                  300
                         UDConS3-1 0                  300
                         UDConS4-1 0                  300
                         UDConS5-1 0                  300
                         UDConS6-1 0                  300
       C8     15         ULS-1     0                  300
                         ULS-2     0                  300
                         UDConS3-1 0                  300
                         UDConS4-1 0                  300
                         UDConS5-1 0                  300
                         UDConS6-1 0                  300

In [18]:
def get_m1_m2(m_start:float, m_end:float, Pu:float, h:float) -> float:
    m2_minimum = Pu * (15 + 0.03 * h) # 6.6.4.5.4
    if m_start == 0 and m_end == 0:
        m1 = 0
        m2 = m2_minimum
    elif abs(m_start) <= abs(m_end):
        m1 = m_start
        if m_end >= 0:
            m2 = max(m2_minimum,m_end)
        else:
            m2 = min(-1.0 * m2_minimum, m_end)
    else:
        m1 = m_end
        if m_start >= 0:
            m2 = max(m2_minimum,m_start)
        else:
            m2 = min(-1.0 * m2_minimum, m_start)
    Cm = 0.6 - 0.4 * (m1/m2) * -1
    return Cm,m1,m2

result_minor = [get_m1_m2(m_start, m_end, Pu, h) for m_start, m_end, Pu, h in zip(first_df['M2'], last_df['M2'],first_df['P'],first_df['section_width'])]
result_major = [get_m1_m2(m_start, m_end, Pu, h) for m_start, m_end, Pu, h in zip(first_df['M3'], last_df['M3'],first_df['P'],first_df['section_depth'])]
display(result_major)
display(result_minor)

[(0.7785345199454079, 106967559.7, 239656868.0),
 (0.7785345199454079, 106967559.7, 239656868.0),
 (0.8839655712181398, 91606080.6, 129038291.8),
 (0.8839655712181398, 91606080.6, 129038291.8),
 (0.4335470361454107, -28535304.41, 68572655.6),
 (0.4335470361454107, -28535304.41, 68572655.6),
 (0.5537901283186518, -11444004.5, 99061123.38),
 (0.5537901283186518, -11444004.5, 99061123.38),
 (0.5587653940016493, -6731767.35, 65302113.96),
 (0.5587653940016493, -6731767.35, 65302113.96),
 (0.6, 0, 38786284.08),
 (0.6, 0, 38786284.08)]

[(0.43113238026873796, -22768665.79, 53932579.44),
 (0.43113238026873796, -22768665.79, 53932579.44),
 (0.47440228658567, -13393332.82, 42654702.72),
 (0.47440228658567, -13393332.82, 42654702.72),
 (0.6, 0, 26128708.799999997),
 (0.6, 0, 26128708.799999997),
 (0.31158025857634364, 86927356.56, -120556736.0),
 (0.31158025857634364, 86927356.56, -120556736.0),
 (0.27608054020065526, 67736718.83, -83646371.69),
 (0.27608054020065526, 67736718.83, -83646371.69),
 (0.2932925276309322, -30434197.78, 39691498.28),
 (0.2932925276309322, -30434197.78, 39691498.28)]

In [22]:
def get_Cm(m_start:float, m_end:float) -> float:
    if abs(m_start) <= abs(m_end):
        m1 = m_start
        m2 = m_end
    else:
        m1 = m_end
        m2 = m_start

    if m2 == 0 :
        Cm = 1.0
    else:
        Cm = 0.6 - 0.4 * (m1/m2) * -1 # we flip by -1 to match etabs results
    return Cm

result_minor = [get_Cm(m_start, m_end) for m_start, m_end in zip(first_df['M2'], last_df['M2'])]
result_major = [get_Cm(m_start, m_end) for m_start, m_end in zip(first_df['M3'], last_df['M3'])]
display(result_major)
display(result_minor)

[0.7785345199454079,
 0.7785345199454079,
 0.8839655712181398,
 0.8839655712181398,
 0.4335470361454107,
 0.4335470361454107,
 0.5537901283186518,
 0.5537901283186518,
 0.5537901283411737,
 0.5537901283411737,
 1.0,
 1.0]

[0.39056644412950053,
 0.39056644412950053,
 0.3905664440782589,
 0.3905664440782589,
 1.0,
 1.0,
 0.31158025857634364,
 0.31158025857634364,
 0.27608054020065526,
 0.27608054020065526,
 0.2932925276309322,
 0.2932925276309322]

In [23]:
import mat_ceng as mc

result_minor = [mc.calculate_Cm(m_start, m_end) for m_start, m_end in zip(first_df['M2'], last_df['M2'])]
result_major = [mc.calculate_Cm(m_start, m_end) for m_start, m_end in zip(first_df['M3'], last_df['M3'])]
display(result_major)
display(result_minor)

[0.7785345199454079,
 0.7785345199454079,
 0.8839655712181398,
 0.8839655712181398,
 0.4335470361454107,
 0.4335470361454107,
 0.5537901283186518,
 0.5537901283186518,
 0.5537901283411737,
 0.5537901283411737,
 1.0,
 1.0]

[0.39056644412950053,
 0.39056644412950053,
 0.3905664440782589,
 0.3905664440782589,
 1.0,
 1.0,
 0.31158025857634364,
 0.31158025857634364,
 0.27608054020065526,
 0.27608054020065526,
 0.2932925276309322,
 0.2932925276309322]

In [101]:
mini_df = pd.DataFrame(
    data = {
        "fc_MPa": [20, 25, 30, 28, 40, 45, 32],
        "gamma": [2350, 1700, 2000, 1600, 2300, 2450, 1680],
    }
)


def concrete_elastic_modulus(fc: float, gamma: float) -> float:
    """
    Returns the elastic modulus of concrete based on the f'c and density of the concrete,
    as per CSA A23.3-04 Cl. 8.6.2.2.
    """   
    if 20 <= fc <= 60:
        return 4500 * fc**0.5
    elif 1500 <= gamma <= 2500:
        return (3300 * fc**0.5 + 6900) * (gamma / 2300) ** 1.5
    else:
        return None
    
mini_df["E"] = mini_df.apply(lambda x: concrete_elastic_modulus(x['fc_MPa'], x['gamma']), axis=1)

mini_df

   fc_MPa  gamma             E
0      20   2350  20124.611797
1      25   1700  22500.000000
2      30   2000  24647.515088
3      28   1600  23811.761800
4      40   2300  28460.498942
5      45   2450  30186.917696
6      32   1680  25455.844123

In [114]:
def m2_min(Pu:float, h:float) -> float:
    return Pu * (15 + 0.03 * h) # 6.6.4.5.4

def m2_minimum(Pu:float, h:float, m2:float) -> float:
    m_min = Pu * (15 + 0.03 * h) # 6.6.4.5.4
    m_min = max(m_min, abs(m2)) * np.sign(m2)
    return m_min

In [15]:
m2_minimum(2247.1908e3,300,43.4862)/1e6

53.93257919999999